export const headerPurple = '#3A455C'
export const headerBottomShadow = '#757575'
export const searchDropdownGrey = '#E7E7EB'
export const mainContentGrayBackground = '#D5D5D6'
export const cardSubtitleGrey = 'grey'
export const cardPriceRed = '#C4402F'
export const cardStarColor = 'orange'